name: Sos Grower
favicon: null
layout_spectrum: 0.2712251970078796
typography_spectrum: 0.24086822592653334
title: 'Helping you grow better!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050402'
    - '#453b31'
    - '#8b7554'
    - '#ad9b6b'
    - '#c6bea3'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
